//Add resident
export const ADD_RESIDENT_SUCCESS="ADD_RESIDENT_SUCCESS";
export const ADD_RESIDENT_FAILED="ADD_RESIDENT_FAILED";
export const LOADING_ADD_RESIDENT="LOADING_ADD_RESIDENT";
export const RESET_ADD_RESIDENT="RESET_ADD_RESIDENT";
export const ADD_RESIDENT_NETWORK_FAILURE="ADD_RESIDENT_NETWORK_FAILURE";

//Update resident
export const UPDATE_RESIDENT_SUCCESS="UPDATE_RESIDENT_SUCCESS";
export const UPDATE_RESIDENT_FAILED="UPDATE_RESIDENT_FAILED";
export const LOADING_UPDATE_RESIDENT="LOADING_UPDATE_RESIDENT";
export const RESET_UPDATE_RESIDENT="RESET_UPDATE_RESIDENT";
export const UPDATE_RESIDENT_NETWORK_FAILURE="UPDATE_RESIDENT_NETWORK_FAILURE";

//Delete resident
export const DELETE_RESIDENT_SUCCESS="DELETE_RESIDENT_SUCCESS";
export const DELETE_RESIDENT_FAILED="DELETE_RESIDENT_FAILED";
export const LOADING_DELETE_RESIDENT="LOADING_DELETE_RESIDENT";
export const RESET_DELETE_RESIDENT="RESET_DELETE_RESIDENT";
export const DELETE_RESIDENT_NETWORK_FAILURE="DELETE_RESIDENT_NETWORK_FAILURE";

//Add visitor
export const ADD_VISITOR_SUCCESS="ADD_VISITOR_SUCCESS";
export const ADD_VISITOR_FAILED="ADD_VISITOR_FAILED";
export const LOADING_ADD_VISITOR="LOADING_ADD_VISITOR";
export const RESET_ADD_VISITOR="RESET_ADD_VISITOR";
export const ADD_VISITOR_NETWORK_FAILURE="ADD_VISITOR_NETWORK_FAILURE";

//Update visitor 
export const UPDATE_VISITOR_SUCCESS="UPDATE_VISITOR_SUCCESS";
export const UPDATE_VISITOR_FAILED="UPDATE_VISITOR_FAILED";
export const LOADING_VISITOR_RESIDENT="LOADING_VISITOR_RESIDENT";
export const RESET_VISITOR_RESIDENT="RESET_VISITOR_RESIDENT";
export const UPDATE_VISITOR_NETWORK_FAILURE="UPDATE_VISITOR_NETWORK_FAILURE";

//Delete visitor
export const DELETE_VISITOR_SUCCESS="DELETE_VISITOR_SUCCESS";
export const DELETE_VISITOR_FAILED="DELETE_VISITOR_FAILED";
export const LOADING_DELETE_VISITOR="LOADING_DELETE_VISITOR";
export const RESET_DELETE_VISITOR="RESET_DELETE_VISITOR";
export const DELETE_VISITOR_NETWORK_FAILURE="DELETE_VISITOR_NETWORK_FAILURE";